<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "wallio"
 *
 * Auto generated by Extension Builder 2019-07-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'chr_wallsio',
    'description' => 'integrates walls.io',
    'category' => 'plugin',
    'author' => 'Christian Rath',
    'author_email' => 'christian.rath@publicispixelpark.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],

];
